"""add_explanation_and_expand_question

Revision ID: 8a30d1aa1d7a
Revises: 
Create Date: 2026-04-12 17:00:51.151296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a30d1aa1d7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('identifier', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('dificultad', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('question_type', sa.String(), nullable=True, server_default='seleccion'))
    op.add_column('questions', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('visual_url', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('audio_url', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('source', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('questions', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('questions', 'options',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_questions_bloque'), 'questions', ['bloque'], unique=False)
    op.create_index(op.f('ix_questions_contenido'), 'questions', ['contenido'], unique=False)
    op.create_index(op.f('ix_questions_grade'), 'questions', ['grade'], unique=False)
    op.create_index(op.f('ix_questions_identifier'), 'questions', ['identifier'], unique=True)
    op.create_index(op.f('ix_questions_subject'), 'questions', ['subject'], unique=False)
    op.create_foreign_key(None, 'questions', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_index(op.f('ix_questions_subject'), table_name='questions')
    op.drop_index(op.f('ix_questions_identifier'), table_name='questions')
    op.drop_index(op.f('ix_questions_grade'), table_name='questions')
    op.drop_index(op.f('ix_questions_contenido'), table_name='questions')
    op.drop_index(op.f('ix_questions_bloque'), table_name='questions')
    op.alter_column('questions', 'options',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('questions', 'updated_at')
    op.drop_column('questions', 'created_by')
    op.drop_column('questions', 'is_active')
    op.drop_column('questions', 'source')
    op.drop_column('questions', 'audio_url')
    op.drop_column('questions', 'visual_url')
    op.drop_column('questions', 'explanation')
    op.drop_column('questions', 'question_type')
    op.drop_column('questions', 'dificultad')
    op.drop_column('questions', 'identifier')
    # ### end Alembic commands ###
